name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- python=3.5
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- ipywidgets==5.2.2
- notebook>=4.2.1
- pip:
  - sphinx==1.4.5
  - nbsphinx==0.2.7
  - jupyter_sphinx_theme==0.0.6
