name: ipywidget_docs
channels:
- conda-forge
- defaults
dependencies:
- python=3.5
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- ipywidgets
- notebook>=4.2
- ipykernel
- pip:
  - sphinx==1.5a1
  - nbsphinx==0.2.9
  - sphinx_rtd_theme==0.1.10-alpha
  - python-dateutil
  - recommonmark==0.4.0
