name: ipywidget_docs
channels:
- conda-forge
dependencies:
- python=3.5
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- jupyter_client
- ipykernel
- ipywidgets
- pip:
  - sphinx==1.4.5
  - nbsphinx==0.2.8
  - jupyter_sphinx_theme==0.0.6
